### ISSUE TITLE
Handling misconfigured provider errors

### ISSUE THREAD

**Issue by AlexFergs** [simov/purest#20]
It seems that grant errors with it's own error message and a 200 when you navigate to 

`/connect/sdsdlknlaslfkdm` 

For example.

Is there a way we can trigger a handle-able error for this?

**Comment by simov** [comment]
I should probably set the status code to something other than 200. After that you will be able to handle the error based on the response's status code.

**Comment by simov** [comment]
Currently the only way to check for errors is to check whether the response body have an `error` key in it.

**Comment by AlexFergs** [comment]
Do you have any time to make an update? I'd be happy to raise a PR for it!

Cheers
Alex

**Comment by simov** [comment]
Yes, I'm going to add a more appropriate error code and tests for it. It'll probably take me a day or two to get to it, hopefully it's not _that_ urgent for you.

**Comment by AlexFergs** [comment]
No I have a workaround for now, but thank you for looking at it! 
Here's my workaround if anyone's interested:

```javascript
app.get(['/connect/:provider'], function(req, res, next){
if (req.params.provider === 'login' || req.params.provider === 'otherProvider') {
    next()
} else {
    res.redirect('/error')
  }
})
app.use(grant)
```

Cheers
Alex

**Comment by AlexFergs** [comment]
Just realised i've raised this on the wrong project!

**Comment by simov** [comment]
Not a problem :)

**Comment by simov** [comment]
@AlexFergs on a second thought that's not a Grant's problem :)

Grant always redirects you to the URL that you specify through the `callback` key in your configuration. The reason why the error is encoded in the querystring is because this type of OAuth flow involves human interaction and a browser. So that's the most reliable way to return something back to the user.

Once Grant redirects you back to your final `callback` route it's your own responsibility to decide what you want to do next. The error is *aways* returned in the querystring as `{error: {....}}` so it's up to you to return some error status code if you want.

Let me know if that makes sense, or if you need an example.

**Comment by AlexFergs** [comment]
So if I have a globally defined callback, any mismatching provider 
e.g `/connect/unconfigured_provider` 
It will always hit that callback?

**Comment by AlexFergs** [comment]
@simov Ah I see, I was missing a global callback in my settings! Thanks for your help!

**Comment by simov** [comment]
@AlexFergs I'm copy/pasting your comments here, because I think they contain valuable information, but for some reason are missing from this thread:

> So if I have a globally defined callback, any mismatching provider
e.g /connect/unconfigured_provider
It will always hit that callback?

> @simov Ah I see, I was missing a global callback in my settings! Thanks for your help!

Yep, that sounds like a good solution to me.

I'm closing this issue now, feel free to open another issue if you have more questions, this time in the Grant repo :)
