### ISSUE TITLE
works with "any HTTP client library" doesn't seem to be true

### ISSUE THREAD

**Issue by jazoom** [simov/purest#28]
I might be misunderstanding something, but when I tried to use my HTTP client library of choice ([superagent](https://github.com/visionmedia/superagent)) Purest hung indefinitely until I exited the process.

This works:
```
const request = require('request');
const purest = require('purest')({ request, promise: Promise });
```

This doesn't work:
```
const request = require('superagent');
const purest = require('purest')({ request, promise: Promise });
```

**Comment by simov** [comment]
Any HTTP client library that implements the [common interface](https://github.com/request/interface). Basically you can have a thin wrapper around `superagent` and pass that wrapper to Purest.

Obviously I don't have such wrapper for every HTTP client, but I agree that the documentation might be a little bit misleading.

**Comment by jazoom** [comment]
I do feel it is misleading and caused me to waste time. I'm really loving `grant` and `purest`. I don't think you need to use that untrue statement to get people to use the library. It's already great with what it actually does.

**Comment by simov** [comment]
I agree.

I guess I got a bit carried out with the use of the word _any_ because it's certainly true for Promise implementations and REST APIs, but not so much for HTTP clients apparently. 

Probably I had the intention to create those wrappers, can't tell you for sure. Currently only [request](https://github.com/request/request) and [@request/client](https://www.npmjs.com/package/@request/client) fully implement the interface. [@request/core](https://github.com/request/core) was my attempt to rewrite request long time ago, and it was covering the entire request test suit at that time, so it's pretty stable and feature rich as it is. I always pair it with Purest, however the code base suffers from other issues and I can't recommend using it because no one is maintaining it. You can try it out of course and see if it works for you as it is.

Anyway, thanks for your feedback! I'm going to update the readme and phrase it more correctly.  :+1:

**Comment by jazoom** [comment]
I'm happy to use it with `request`. I do use request for some purposes that require complex proxy handling so I'm not opposed to the library. I just prefer `superagent`. It's no big deal including `request` as a dependency and passing it to Purest.

**Comment by bitinn** [comment]
Out of curiosity, what does `grant` use underneath? Is it `request` or some other rewrite of it? I am happy to see `purest` remove the *any http library* slogan and just use the same http lib as `grant`, if possible.

PS: I wrote node-fetch, so I am biased in wanting to use a lighter http lib :)

**Comment by bitinn** [comment]
Another thing I find super weird: promise api already return both full response and the body. But it's not mentioned anywhere in doc.

https://github.com/simov/purest/blob/master/test/promise.js#L40-L52

**Comment by simov** [comment]
Hi @bitinn, Grant uses [request-compose](https://github.com/simov/request-compose) under the hood. It's my latest (and greatest) [HTTP client for Node](https://dev.to/simov/composable-http-client-for-nodejs-83f).

It's not exactly a rewrite of [request](https://github.com/request/request) and that have never been the goal, even though the [multipart](https://github.com/simov/request-multipart), [oauth](https://github.com/simov/request-oauth) and [cookie](https://github.com/simov/request-cookie) 'middlewares' are taken straight from request. They were initially extracted out for my actual rewrite, [@request/core](https://github.com/request/core), a few years ago. [request-logs](https://github.com/simov/request-logs) is taken from [@request/log](https://github.com/request/log) initially implemented for @request/core.

It's possible to add request-compose as optional HTTP client here, unfortunately it can't be set as default one without major release, because it have some differences with request, namely it's not a duplex stream, and also it doesn't implement the [@request/interface](https://github.com/request/interface) strictly. And this is going to be yet another breaking change and not fully backward compatible version.

**Comment by simov** [comment]
No longer applicable. Purest v4 was migrated to use request-compose under the hood. It is a major breaking change for the configuration data structure as well, check out the documentation and the examples.
